### ISSUE TITLE
Issue in mvn clean install

### ISSUE THREAD

**Issue by ravijp** [avishek-sen-gupta/cobol-rekt#68]
Hi Avishek, 

I am using a windows system and followed the dependency steps. 

When I run `mvn clean install` I get following error - 

![image](https://github.com/user-attachments/assets/a3dc9b43-431f-48ee-99c8-3d8803c03620)

**Comment by avishek-sen-gupta** [comment]
IIRC, this happens when Java 1.8 is not installed (the Che4z compiler support project requires Java 1.8). Could you set up both Java 1.8 and JDK 21 on your machines, and see if the output is any different?

**Comment by ravijp** [comment]
It seems it has to do with cobol dependency and code needs to be updated to refer to correct dependency and use updated functions.

**Comment by avishek-sen-gupta** [comment]
I don't have a Windows machine setup to investigate this. If you are interested in trying out the JAR directly, you can try the [latest build](https://github.com/avishek-sen-gupta/cobol-rekt/releases/tag/0.1.1-RC2), generated directly from the Github Actions pipeline.

**Comment by avishek-sen-gupta** [comment]
For an additional check, I've run the build on a Windows image [here](https://github.com/avishek-sen-gupta/cobol-rekt/actions/runs/11956170617). It builds without any modifications.

**Comment by avishek-sen-gupta** [comment]
For an exhaustive check, I ran the build on a clean Windows local machine (no prior Maven installs, no existing cloned repository). The screenshot shows it passing.
![Screenshot 2024-11-21 214748](https://github.com/user-attachments/assets/c1866369-69a0-4b6f-b925-07ff5b6207ea)

Please run your build once with ```mvn clean verify``` once, and let me know if you see any different.

**Comment by raoalok** [comment]
Machine - Apple M2

JAVA JDK Version - 
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode)

Maven Version - 
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec
Java version: 23.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/23.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "15.1", arch: "aarch64", family: "mac"

Did a git clone and ran "git submodule update --init --recursive" for submodules. Then replaced - 
Alternatively, you can update all occurrences of the following:

<maven.compiler.source>8</maven.compiler.source>
<maven.compiler.target>8</maven.compiler.target>
to

<maven.compiler.source>21</maven.compiler.source>
<maven.compiler.target>21</maven.compiler.target>

...... 

Then ran "mvn clean verify". Getting errors.

![Screenshot 2024-11-21 at 22 02 35](https://github.com/user-attachments/assets/c27298a2-530b-4362-b7b6-10bc6e15e2d3)

@avishek-sen-gupta

**Comment by avishek-sen-gupta** [comment]
> Machine - Apple M2
> 
> JAVA JDK Version - openjdk version "21.0.5" 2024-10-15 LTS OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode)
> 
> Maven Version - Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937) Maven home: /opt/homebrew/Cellar/maven/3.9.9/libexec Java version: 23.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/23.0.1/libexec/openjdk.jdk/Contents/Home Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "15.1", arch: "aarch64", family: "mac"
> 
> Did a git clone and ran "git submodule update --init --recursive" for submodules. Then replaced - Alternatively, you can update all occurrences of the following:
> 
> <maven.compiler.source>8</maven.compiler.source> <maven.compiler.target>8</maven.compiler.target> to
> 
> <maven.compiler.source>21</maven.compiler.source> <maven.compiler.target>21</maven.compiler.target>
> 
> ......
> 
> Then ran "mvn clean verify". Getting errors.
> 
> ![Screenshot 2024-11-21 at 22 02 35](https://private-user-images.githubusercontent.com/24505929/388605542-c27298a2-530b-4362-b7b6-10bc6e15e2d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMDcxMTEsIm5iZiI6MTczMjIwNjgxMSwicGF0aCI6Ii8yNDUwNTkyOS8zODg2MDU1NDItYzI3Mjk4YTItNTMwYi00MzYyLWI3YjYtMTBiYzZlMTVlMmQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE2MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMzY0MjBjYWYxYWQwMzIwZjcyZDA1MmQ1NWI3YjVkY2NhZjA3NzA5MDE3YWJiNzk0MDg4NjQ3MzBhYTAwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4H5aGhkqZtzroUS7TvgApusiiIb8YTdLsKfnLzv3HB4)
> 
> @avishek-sen-gupta

Oh, I noticed you have Java 23. Can you downgrade to JDK 21 or 22 and retry? I remember running into these compile issues when I accidentally upgraded to JDK 23 sometime again.

**Comment by avishek-sen-gupta** [comment]
That is strange. It seems that Maven is not downloading the JGraphT dependency. Could you run the following command ```mvn clean verify -Dmaven.test.skip=true -X``` and post the output in a file somewhere (the debug output would be too big to paste here)? There might be a dependency download failure that's happening on your machine and running it in debug mode may shed some light.

**Comment by avishek-sen-gupta** [comment]
> I did the second step. Replaced '8' with '21'. When I use `mvn clean install` then I get following error -
> 
> ![image](https://private-user-images.githubusercontent.com/16938793/388210315-808f0637-911d-431f-b117-4812157dff15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTI2NTcsIm5iZiI6MTczMjIxMjM1NywicGF0aCI6Ii8xNjkzODc5My8zODgyMTAzMTUtODA4ZjA2MzctOTExZC00MzFmLWIxMTctNDgxMjE1N2RmZjE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlNDM0NTg2ZGMzOTFmZTcxNjkzODQxNDQ4YWY2M2M2MDIzMTdkNWI3MjU0N2UzOTg2ZDc3YzZhMTMyNDVkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3ogtezjMeawBhXFR_cQZhOVuYorIlDjOHBeZ9kw0Ls0)
> 
> So, I try `mvn clean install -Dcheckstyle.skip=true`
> 
> I get following error - ![image](https://private-user-images.githubusercontent.com/16938793/388212030-3371b73b-df2d-4302-afba-311e9e8a99f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTI2NTcsIm5iZiI6MTczMjIxMjM1NywicGF0aCI6Ii8xNjkzODc5My8zODgyMTIwMzAtMzM3MWI3M2ItZGYyZC00MzAyLWFmYmEtMzExZTllOGE5OWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxZjJhMTc0MWVhYTRiOGNiYzhhN2YyMWM4NGE4YzE5ZjZlMTIyNmE4OTRiOWYyZDkxMWU4MjllNTgxMDA1NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Hr2_i11R1RtYp-eFOd3mPk_DNuMfRY0po5NNa9SW4vk)
> 
> I make following changes in
> 
> ```
>  <dependency>
>             <groupId>hu.webarticum</groupId>
>             <artifactId>tree-printer</artifactId>
>             <version>2.2.0</version>
> </dependency>
> ```
> 
> Then after re running it as `mvn clean install -Dcheckstyle.skip=true -Dmaven.test.skip=true -U -rf :smojol-core` I get following error - ![image](https://private-user-images.githubusercontent.com/16938793/388212490-34c48cfd-5dc8-45b9-a94a-11dd17c7e718.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTI2NTcsIm5iZiI6MTczMjIxMjM1NywicGF0aCI6Ii8xNjkzODc5My8zODgyMTI0OTAtMzRjNDhjZmQtNWRjOC00NWI5LWE5NGEtMTFkZDE3YzdlNzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NjVjMjA4MGRhNDA0YTg3YmZkODkxNWUwZWJkMDEwNjY2ODM2OTJlN2NhNTE5NjRhNDc4NjM4ZDY2YjdlYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-Rj9SbNDbCu8XGJB0EJ0GeQmTPmmu64MjKO2tmNY26o)
> 
> So, I add following repository and update the cobol dependency as I was not able to find the parser at location https://packages.broadcom.com/artifactory/brightside-maven/org/eclipse/lsp/cobol/
> 
> ```
> <repositories>
>   <repository>
>       <id>Broadcom</id>
>       <name>Broadcom Inc</name>
>       <url>https://packages.broadcom.com/artifactory/brightside-maven/</url>
>   </repository>
> </repositories>
> 
> <dependency>
>     <groupId>org.eclipse.lsp.cobol</groupId>
>     <artifactId>common</artifactId>
>     <version>1.0.7</version>
> </dependency>
> ```
> 
> I still get the following error, ![image](https://private-user-images.githubusercontent.com/16938793/388214225-14e2ba40-932d-4c51-9cdf-2985f73516bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyMTI2NTcsIm5iZiI6MTczMjIxMjM1NywicGF0aCI6Ii8xNjkzODc5My8zODgyMTQyMjUtMTRlMmJhNDAtOTMyZC00YzUxLTljZGYtMjk4NWY3MzUxNmJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDE4MDU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllNGMyNzQ5YzUyMDQ0MTk0M2U1OGI2ODQ4OWJhZDk4OTkzNzYzYmM2ZjA2NWYxMDhkMWMxZWUwOThlZThiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tTUSlDUwZy_-NbtBUdTvWz0TsaX6Iui36U1v-Cz_d9I)
> 
> I have little to zero experience in Java and wanted to try out this project to see how your ASTs and control flow are looking in Neo4j. @avishek-sen-gupta

Could you run ```mvn --version``` and paste the output, so we can see if it is a similar issue?

**Comment by ravijp** [comment]
After following the latest steps, I am able to build it (in windows). Looking forward to try it out. Thanks for prompt response Avishek. 

![image](https://github.com/user-attachments/assets/5b479253-80a6-44de-9ab4-7ad5a84e69ea)

**Comment by raoalok** [comment]
> That is strange. It seems that Maven is not downloading the JGraphT dependency. Could you run the following command `mvn clean verify -Dmaven.test.skip=true -X` and post the output in a file somewhere (the debug output would be too big to paste here)? There might be a dependency download failure that's happening on your machine and running it in debug mode may shed some light.

https://drive.google.com/file/d/1eGaAKEYlYbdYwDnUdsmVCM2du6n8uU5F/view?usp=sharing

Link of the txt file will all the logs after running "mvn clean verify -Dmaven.test.skip=true -X".

@avishek-sen-gupta

**Comment by avishek-sen-gupta** [comment]
> > That is strange. It seems that Maven is not downloading the JGraphT dependency. Could you run the following command `mvn clean verify -Dmaven.test.skip=true -X` and post the output in a file somewhere (the debug output would be too big to paste here)? There might be a dependency download failure that's happening on your machine and running it in debug mode may shed some light.
> 
> https://drive.google.com/file/d/1eGaAKEYlYbdYwDnUdsmVCM2du6n8uU5F/view?usp=sharing
> 
> Link of the txt file will all the logs after running "mvn clean verify -Dmaven.test.skip=true -X".
> 
> @avishek-sen-gupta

There doesn't seem to be anything obviously wrong in the debug log. Could you try a couple of things?

- Run ```mvn dependency:tree```. In the output, you should be seeing something like this:
<img width="697" alt="Screenshot 2024-11-22 at 1 46 27 AM" src="https://github.com/user-attachments/assets/7ed905e6-c92d-4aa2-81eb-fb628081db34">

- Run ```mvn dependency:purge-local-repository``` to force Maven to re-resolve all dependencies, and then run ```mvn clean verify -Dmaven.test.skip=true -X``` as before.

**Comment by raoalok** [comment]
> > > That is strange. It seems that Maven is not downloading the JGraphT dependency. Could you run the following command `mvn clean verify -Dmaven.test.skip=true -X` and post the output in a file somewhere (the debug output would be too big to paste here)? There might be a dependency download failure that's happening on your machine and running it in debug mode may shed some light.
> > 
> > 
> > https://drive.google.com/file/d/1eGaAKEYlYbdYwDnUdsmVCM2du6n8uU5F/view?usp=sharing
> > Link of the txt file will all the logs after running "mvn clean verify -Dmaven.test.skip=true -X".
> > @avishek-sen-gupta
> 
> There doesn't seem to be anything obviously wrong in the debug log. Could you try a couple of things?
> 
> * Run `mvn dependency:tree`. In the output, you should be seeing something like this:
> 
> <img alt="Screenshot 2024-11-22 at 1 46 27 AM" width="697" src="https://private-user-images.githubusercontent.com/166610690/388679811-7ed905e6-c92d-4aa2-81eb-fb628081db34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNDUwMjksIm5iZiI6MTczMjI0NDcyOSwicGF0aCI6Ii8xNjY2MTA2OTAvMzg4Njc5ODExLTdlZDkwNWU2LWM5MmQtNGFhMi04MWViLWZiNjI4MDgxZGIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQwMzA1MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWNjMGExZTVlZWQ5MTczNTEwN2Y2MmI2YzAzOTQ2YjFiMGQxYjg1ZmM3ZjA4ZTc5NjJlYzAyY2VmMmJiMDcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TviZRyyCpmpT3QbWLiBUKfJAyjYJyhESE71pA2WBXMo">
> * Run `mvn dependency:purge-local-repository` to force Maven to re-resolve all dependencies, and then run `mvn clean verify -Dmaven.test.skip=true -X` as before.



https://drive.google.com/file/d/1Rb327hvpZKRlTOmdu4kMEUvQGugTDTNj/view?usp=sharing

Link of the txt file will all the logs. First two commands run with success, last one got error.

**Comment by avishek-sen-gupta** [comment]
The relevant warning seems to be this:
```
[WARNING] location of system modules is not set in conjunction with -source 21
  not setting the location of system modules may lead to class files that cannot run on JDK 21
    --release 21 is recommended instead of -source 21 -target 21 because it sets the location of system modules automatically
```

Resolving this depends upon how your JDK is set up, but as a check, you can clone and try building the original [Che4z repository](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol) separately. If that one compiles successfully, this repo should also compile.

**Comment by raoalok** [comment]
> The relevant warning seems to be this:
> 
> ```
> [WARNING] location of system modules is not set in conjunction with -source 21
>   not setting the location of system modules may lead to class files that cannot run on JDK 21
>     --release 21 is recommended instead of -source 21 -target 21 because it sets the location of system modules automatically
> ```
> 
> Resolving this depends upon how your JDK is set up, but as a check, you can clone and try building the original [Che4z repository](https://github.com/eclipse-che4z/che-che4z-lsp-for-cobol) separately. If that one compiles successfully, this repo should also compile.


Thanks for the help. It's resolved.
